name: Algorithms Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [python, dotnet, node]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Python
      - name: Set up Python tests
        if: matrix.language == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run Python tests
        run: |
          python -m pip install --upgrade pip
          pip install -r src/Python/requirements.txt
          pytest tests/Python

      # C#
      - name: Set up .NET tests
        if: matrix.language == 'dotnet'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run .NET tests
        run: dotnet test tests/C#

      # JavaScript
      - name: Set up JavaScript tests
        if: matrix.language == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run JavaScript tests
        run: |
          cd src/JavaScript
          npm ci
          npm test
